### ISSUE TITLE
Can this be applicable for more than 1 classes?

### ISSUE THREAD

**Issue by iqrammm** [michhar/pytorch-yolo-v3-custom#1]
I wanted to do object detection to detect two different classes,it it possible? Because I saw your comment saying it is for one classes.

**Comment by vkrd** [comment]
I am pretty sure this can be used to detect multiple classes if you go to the tiny yolo configuration file and change the filters to `filters=(classes + 5)x3` and `classes` to the appropriate number of classes. You will probably also have to update the "obj.data" and "obj.names" files.

**Comment by michhar** [comment]
@iqrammm - Yes, @vkrd is correct.  Just change the appropriate config file `filters` and `classes`.

https://github.com/michhar/pytorch-yolo-v3-custom#modifications-for-custom

I will, also, shortly be checking in an example config file for 2-class along with many other updates, but in general any number of classes may be used.  Thank you for your interest!

**Comment by iqrammm** [comment]
![image](https://user-images.githubusercontent.com/48657762/62348884-b61e2f80-b530-11e9-919e-2a116761bfbb.png)

After training,I got the error above?by any chance u encounter such error?

**Comment by michhar** [comment]
@iqrammm Hello.  I believe the issue might be that the YOLO v2000 is a different architecture from YOLO v3.  Could you try the one listed in Setup instead to test?  https://github.com/michhar/pytorch-yolo-v3-custom#setup

Also, how many classes do you have?  We could check the config file as well.

Thanks.

**Comment by iqrammm** [comment]
Got the same error even when using the official yolov3 weights.

Here is my cfg : https://pastebin.com/DSkRJg9Q

**Comment by michhar** [comment]
@iqrammm I missed the command in screenshot, but now see...`live.py` will only work on PyTorch weights and you are actually using Darknet weights if I am not mistaken.  The training script saves the PyTorch weights as `.pth` files under the `runs` directory.  Could you try a PyTorch model?

**Comment by michhar** [comment]
Closing as problem addressed.  Feel free to continue discussion, of course.  Thanks!
