### ISSUE TITLE
will this work on cpu? 

### ISSUE THREAD

**Issue by vaibhavkumar049** [michhar/pytorch-yolo-v3-custom#5]
I don't have GPU or nvidia GPU will that possible ton CPU? anyone done it? I just have to localize text

**Comment by michhar** [comment]
Hi @vaibhavkumar049.  Yes, this will work on CPU and this is where most testing is done, actually.  However, this project is undergoing some fixes to big issues so please take that in to consideration.  This is a hobby project right now for me.  I'll put a note on the main readme when it's more stable, of course.  Thank for your interest, however!  Feel free to post more issues as they come up.  The main one I'm seeing now is the training is not converging well.  Just want to give warning.

**Comment by michhar** [comment]
Closing, but feel free to comment, still if there are more issues related to this.  Thanks.
