### ISSUE TITLE
Nameerror: name 'model_dim' is not defined

### ISSUE THREAD

**Issue by xujianshu** [michhar/pytorch-yolo-v3-custom#9]
Hi, when I was running detect.py it seems the code didn't define 'model_dim', and 'orig_dim' but need them for  'prediction = write_results(prediction, confidence, num_classes, model_dim, orig_dim, nms = True, nms_conf = nms_thesh)'?

**Comment by michhar** [comment]
Hi @xujianshu.  Thank you for your issue and interest!  I'll look at this problem shortly and post here when I have a fix.

**Comment by michhar** [comment]
@xujianshu I will remove this script from the repo.  I do not use it, actually - an artifact from the fork.  Sorry for causing confusion.  Please try `eval.py --help` and follow those instructions and post here if you run into an issue.  Thank you.

**Comment by michhar** [comment]
Closing, but feel free to comment if still encountering issues related to this.  Thanks.
